from . import trainingPlan
from . import typeOfTraining
from . import fieldOfStudy
from . import levelOfStudy
from . import training
from . import end_of_course_evaluation
from . import post_training_evaluation
from . import supervisors_post_training_evaluation
from . import provinces
from . import sponsor
from . import trainingInstitution
from . import zaneqasTbXpertEqaResults
from . import zaneqasTbXpertEqaResultsLines
from . import zaneqasTbXpertEqaResultsErrorCodeLines
from . import zaneqasTbXpertEqaExpectedResults
from . import zaneqasTbXpertEqaExpectedResultsLines
from . import zaneqas_tb_xpert_eqa_results_report
from . import zaneqasTbXpertEqaConfigRounds
from . import zaneqasTbXpertEqaConfigAssays
from . import zaneqasTbXpertEqaRoundLines
