# -*- coding: utf-8 -*-
###############################################################################
#
#    Copyright (C) 2024
#
#
###############################################################################

{
    'name': 'HRMS Core',
    'version': '17.0.1.0',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    "sequence": 1,
    'summary': 'Human Resource Management System',
    'complexity': "easy",
    'author': 'Ministry of Health',
    'website': 'https://www.moh.gov.zm',
    'depends': [
        'base',
        'mail',
        'calendar',
        'board',
        'hr',
        'contacts',
        'hr_contract',
        # 'hr_appraisal',
        # 'hr_appraisal_contract',
        # 'hr_appraisal_skills',
        # 'hr_appraisal_survey',
        'muk_web_theme',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/res.groups.xml',
        'views/hr_department_views.xml',
        'views/departmental_work_plan_views.xml',
        'views/strategic_plan_views.xml',
        'views/hr_employee_views.xml',
        'views/qualification_level_views.xml',
        'views/competence_views.xml',
        'views/qualification_views.xml',
        'views/res_partner_views.xml',
        'views/res_company_views.xml',
        'views/isco_08_views.xml',
        'views/who_cadre_views.xml',
        'views/cadre_views.xml',
        'views/salary_grade_views.xml',
        'views/funder_views.xml',
        'views/job_classification_views.xml',
        'views/hrms_job_views.xml',
        'views/hr_job_views.xml',
        'views/job_description_views.xml',
        'menus/hrms_core_menus.xml',
        'data/ir_sequence_data.xml',
        'data/qualification_levels_data.xml',
        'data/qualifications_data.xml',
        'data/competences_data.xml',
        'data/hrms_partner_data.xml',
        'data/training_institutions_data.xml',
        'data/organisation_units_data.xml',
        'data/isco_08_data.xml',
        'data/who_cadre_categories_data.xml',
        'data/who_cadres_data.xml',
        'data/cadres_data.xml',
        'data/salary_grades_data.xml',
        'data/funders_data.xml',
        'data/job_classifications_data.xml',
        'data/departments_data.xml',
        'data/jobs_data.xml',
    ],
    'demo': [],
    'css': [],
    'qweb': [],
    'js': [],
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': True,

    'assets': {
        'website.assets_frontend': [],
        'web.assets_backend': [],
    },
}
